### ISSUE TITLE
[Bug]无法更改名称，取不到`CPU_LOAD`和`MEMORY_LOAD`的值

### ISSUE THREAD

**Issue by Aigio1064** [PigeonYuze/GroupBotSuffix#13]
Mirai版本：2.15.0
插件版本：1.3.0
配置：
```YAML
mode: LAZY
waitTimeMS: 30000
waitGroupMS: 300
isOpenRandomTime: true
open: CPU_LOAD
content: 猫脑负载 %s
separator: ' | '
allowlist: 
  - '*'
```
在设置`open`的值为`CPU_LOAD`和`MEMORY_LOAD`后，弹出了错误
```plant
2023-08-31 16:31:36 E/GroupBotSuffix: Exception in coroutine Plugin com.pigeonyuze.group-bot-suffix of GroupBotSuffix
java.lang.RuntimeException: 出现了意向不到的错误: 找不到新的名称. 请将以下数据反馈到 git 仓库
将要修改的群目标: ******** 运行时数据: {} , {}
        at GroupBotSuffix-1.3.0.mirai2.jar//com.pigeonyuze.GroupBotSuffix$onEnable$1.invokeSuspend(GroupBotSuffix.kt:96)
        at GroupBotSuffix-1.3.0.mirai2.jar//com.pigeonyuze.GroupBotSuffix$onEnable$1.invoke(GroupBotSuffix.kt)
        at GroupBotSuffix-1.3.0.mirai2.jar//com.pigeonyuze.GroupBotSuffix$onEnable$1.invoke(GroupBotSuffix.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:480)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
        at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
        at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
        at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:120)
        at net.mamoe.mirai.internal.event.EventListeners.callListeners$mirai_core(EventListeners.kt:68)
        at net.mamoe.mirai.internal.event.EventChannelImpl.callListeners(EventChannelImpl.kt:85)
        at net.mamoe.mirai.internal.event.EventChannelImpl.broadcastEventImpl(EventChannelImpl.kt:75)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast$suspendImpl(EventDispatcher.kt:99)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast(EventDispatcher.kt)
        at net.mamoe.mirai.internal.MiraiImpl.broadcastEvent$suspendImpl(MiraiImpl.kt:237)
        at net.mamoe.mirai.internal.MiraiImpl.broadcastEvent(MiraiImpl.kt)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:161)
        at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.broadcastMessagePreSendEvent(GroupSendMessageImpl.kt:35)
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:260)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage$suspendImpl(GroupImpl.kt:221)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage(GroupImpl.kt)
        at net.mamoe.mirai.contact.Group$sendMessage$1.invoke(Group.kt)
        at net.mamoe.mirai.contact.Group$sendMessage$1.invoke(Group.kt)
        at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at me.him188.kotlin.jvm.blocking.bridge.internal.RunSuspendKt.$runSuspend$(RunSuspend.kt:18)
        at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)
        at AutoReply-1.2.1.mirai2.jar//io.github.kloping.autoReply.OnCommand.lambda$schedule$1(OnCommand.java:73)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)

```

**Comment by Aigio1064** [comment]
但是默认的配置可以成功应用上

**Comment by Aigio1064** [comment]
但是......重载配置后又不报错了.....还能用了！离谱！
